import { Amplify } from 'aws-amplify';

/**
 * Configure Amplify with the generated outputs
 * This file will be generated automatically when you run `npx ampx sandbox` or deploy
 * For development, you can create a local amplify_outputs.json file
 */
let outputs: any;
try {
  // Try to import the outputs file (generated by Amplify)
  outputs = require('../amplify_outputs.json');
} catch (error) {
  console.warn('amplify_outputs.json not found. Please run `npx ampx sandbox` or deploy your backend.');
  // Provide a minimal config structure to prevent crashes during development
  outputs = {
    version: '1',
    auth: {
      user_pool_id: '',
      user_pool_client_id: '',
      identity_pool_id: '',
    },
  };
}

console.log('[AMPLIFY] Configuring Amplify...');
console.log('[AMPLIFY] Auth config:', {
  userPoolId: outputs.auth?.user_pool_id,
  region: outputs.auth?.aws_region,
  clientId: outputs.auth?.user_pool_client_id
});
Amplify.configure(outputs, {
  ssr: true,
});
console.log('[AMPLIFY] Configuration complete');

